# Generated by Django 4.2.2 on 2023-08-14 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to='', verbose_name='Логотип картинкой')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='Логотип ссылкой')),
            ],
            options={
                'verbose_name': 'Логотип',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to='', verbose_name='Фото картинкой')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='Фото ссылкой')),
                ('status', models.CharField(choices=[('men', 'Мужские образы'), ('men_base', 'Мужское на главной'), ('women', 'Женские образы'), ('women_base', 'Женское на главной'), ('contacts', 'Контакты'), ('about', 'О нас')], max_length=100, verbose_name='Раздел сайта')),
            ],
            options={
                'verbose_name': 'Фото',
                'verbose_name_plural': 'Фото',
            },
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст')),
                ('status', models.CharField(choices=[('ship', 'Доставка'), ('return', 'Возврат'), ('payment', 'Оплата'), ('about', 'О нас'), ('contacts', 'Контакты')], max_length=100, verbose_name='Раздел сайта')),
            ],
            options={
                'verbose_name': 'Текст',
                'verbose_name_plural': 'Текст',
            },
        ),
    ]
