# Generated by Django 4.2.2 on 2023-08-14 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setups', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logo',
            options={'verbose_name': 'Логотип', 'verbose_name_plural': 'Логотипы'},
        ),
        migrations.RemoveField(
            model_name='logo',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='image_url',
        ),
        migrations.AlterField(
            model_name='logo',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Логотип'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Фото'),
        ),
    ]
