# Generated by Django 4.2.2 on 2023-08-15 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setups', '0003_alter_photo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='status',
            field=models.CharField(choices=[('men', 'Мужские образы'), ('men_base', 'Мужское на главной'), ('women', 'Женские образы'), ('women_base', 'Женское на главной'), ('about', 'О нас')], max_length=100, verbose_name='Раздел сайта'),
        ),
    ]
