# Generated by Django 4.2.2 on 2023-08-14 15:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Промокод')),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='Описание')),
                ('discount', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'verbose_name': 'Промокоды',
                'verbose_name_plural': 'Промокод',
                'ordering': ['code'],
            },
        ),
    ]
