# Generated by Django 4.2.2 on 2023-08-14 15:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100, verbose_name='Адрес')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Телефон')),
                ('ready_to_spam', models.BooleanField(default=False, verbose_name='Подписка на рассылку')),
                ('verification_token', models.CharField(blank=True, max_length=255, null=True)),
                ('is_verify', models.BooleanField(default=False, null=True, verbose_name='Подтвержденный аккаунт')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
